-- Seed Turkish news sources (145 outlets) with full bias taxonomy and source kind.
-- kind is one of 'outlet' | 'aggregator' | 'wire' | 'niche' — see
-- supabase/functions/_shared/cluster/source-kind.ts. Only outlet and wire vote
-- toward bias_distribution / blindspot / trends; the rest default to 'outlet'
-- unless listed otherwise below. Source: turkish_news_rss_database_v2.xlsx.
-- Safe to re-run.

insert into sources (name, slug, url, rss_url, bias, kind, active) values
  -- Pro-Government
  ('Sabah', 'sabah', 'https://www.sabah.com.tr', 'https://www.sabah.com.tr/rss/gundem.xml', 'pro_government', 'outlet', true),
  ('A Haber', 'a-haber', 'https://www.ahaber.com.tr', 'https://www.ahaber.com.tr/rss/gundem.xml', 'pro_government', 'outlet', true),
  ('Yeni Şafak', 'yeni-safak', 'https://www.yenisafak.com', 'https://www.yenisafak.com/rss?xml=gundem', 'pro_government', 'outlet', true),
  ('Yeni Akit', 'yeni-akit', 'https://www.yeniakit.com.tr', 'https://www.yeniakit.com.tr/rss/haber/gundem', 'pro_government', 'outlet', true),
  ('Star', 'star', 'http://www.star.com.tr', 'http://www.star.com.tr/rss/sondakika.xml', 'pro_government', 'outlet', true),
  ('Takvim', 'takvim', 'https://www.takvim.com.tr', 'https://www.takvim.com.tr/rss/anasayfa.xml', 'pro_government', 'outlet', true),
  ('Diriliş Postası', 'dirilis-postasi', 'https://www.dirilispostasi.com', 'https://www.dirilispostasi.com/rss', 'pro_government', 'outlet', true),
  ('Türkiye Gazetesi', 'turkiye-gazetesi', 'https://www.turkiyegazetesi.com.tr', 'https://www.turkiyegazetesi.com.tr/rss/rss.xml', 'pro_government', 'outlet', true),
  ('GZT', 'gzt', 'https://www.gzt.com', 'https://www.gzt.com/rss', 'pro_government', 'outlet', true),
  ('Vahdet', 'vahdet', 'https://www.vahdet.com.tr', 'https://www.vahdet.com.tr/rss', 'pro_government', 'outlet', false),
  ('Yenisöz', 'yenisoz', 'https://www.yenisoz.com.tr', 'https://www.yenisoz.com.tr/rss', 'pro_government', 'outlet', false),
  ('İstiklal', 'istiklal', 'https://www.istiklal.com.tr', 'https://www.istiklal.com.tr/rss', 'pro_government', 'outlet', false),
  ('A Spor', 'a-spor', 'https://www.aspor.com.tr', 'https://www.aspor.com.tr/rss/anasayfa.xml', 'pro_government', 'niche', true),

  -- Gov-Leaning
  ('Habertürk', 'haberturk', 'https://www.haberturk.com', 'https://www.haberturk.com/rss', 'gov_leaning', 'outlet', true),
  ('Hürriyet', 'hurriyet', 'https://www.hurriyet.com.tr', 'https://www.hurriyet.com.tr/rss/anasayfa', 'gov_leaning', 'outlet', true),
  ('Milliyet', 'milliyet', 'http://www.milliyet.com.tr', 'http://www.milliyet.com.tr/rss/rssNew/gundemRss.xml', 'gov_leaning', 'outlet', true),
  ('CNN Türk', 'cnn-turk', 'https://www.cnnturk.com', 'https://www.cnnturk.com/feed/rss/all/news', 'gov_leaning', 'outlet', true),
  ('NTV', 'ntv', 'https://www.ntv.com.tr', 'https://www.ntv.com.tr/gundem.rss', 'gov_leaning', 'outlet', true),
  ('Posta', 'posta', 'http://www.posta.com.tr', 'http://www.posta.com.tr/xml/rss/rss_3_0.xml', 'gov_leaning', 'outlet', true),
  ('Akşam', 'aksam', 'https://www.aksam.com.tr', 'https://www.aksam.com.tr/rss/rss.asp', 'gov_leaning', 'outlet', true),
  ('Güneş', 'gunes', 'https://www.gunes.com', 'https://www.gunes.com/rss', 'gov_leaning', 'outlet', false),
  ('Yeni Asır', 'yeni-asir', 'https://www.yeniasir.com.tr', 'https://www.yeniasir.com.tr/rss/anasayfa.xml', 'gov_leaning', 'outlet', true),
  ('Milat', 'milat', 'http://www.milatgazetesi.com', 'http://www.milatgazetesi.com/rss.php', 'gov_leaning', 'outlet', true),
  ('Şok', 'sok', 'https://www.sok.com.tr', 'https://www.sok.com.tr/rss', 'gov_leaning', 'outlet', false),
  ('En Son Haber', 'en-son-haber', 'https://www.ensonhaber.com', 'https://www.ensonhaber.com/rss/ensonhaber.xml', 'gov_leaning', 'outlet', true),
  ('Mynet', 'mynet', 'https://www.mynet.com', 'https://www.mynet.com/haber/rss/sondakika', 'gov_leaning', 'outlet', true),
  ('Haber Global', 'haber-global', 'https://haberglobal.com.tr', 'https://haberglobal.com.tr/rss', 'gov_leaning', 'outlet', true),
  ('İnternet Haber', 'internet-haber', 'https://www.internethaber.com', 'https://www.internethaber.com/rss', 'gov_leaning', 'outlet', true),
  ('Haber7', 'haber7', 'https://www.haber7.com', 'https://i12.haber7.net/sondakika/newsstand/latest.xml', 'gov_leaning', 'outlet', true),
  ('TGRT Haber', 'tgrt-haber', 'http://www.tgrthaber.com.tr', 'http://www.tgrthaber.com.tr/feed/index.rss', 'gov_leaning', 'outlet', false),
  ('Haberler.com', 'haberler-com', 'https://www.haberler.com', 'https://rss.haberler.com/RssNew.aspx', 'gov_leaning', 'aggregator', true),
  ('DHA', 'dha', 'http://www.dha.com.tr', 'http://www.dha.com.tr/rss.asp', 'gov_leaning', 'wire', false),
  ('İHA', 'iha', 'http://www.iha.com.tr', 'http://www.iha.com.tr/rss.aspx', 'gov_leaning', 'wire', false),
  ('Fotomaç', 'fotomac', 'https://www.fotomac.com.tr', 'https://www.fotomac.com.tr/rss/anasayfa.xml', 'gov_leaning', 'niche', true),
  ('Fanatik', 'fanatik', 'https://www.fanatik.com.tr', 'https://www.fanatik.com.tr/rss/anasayfa.xml', 'gov_leaning', 'niche', true),
  ('NTV Spor', 'ntv-spor', 'https://www.ntvspor.net', 'https://www.ntvspor.net/rss/anasayfa', 'gov_leaning', 'niche', true),
  ('BigPara', 'bigpara', 'http://bigpara.hurriyet.com.tr', 'http://bigpara.hurriyet.com.tr/rss/', 'gov_leaning', 'niche', true),

  -- State Media
  ('Anadolu Ajansı', 'anadolu-ajansi', 'https://www.aa.com.tr', 'https://www.aa.com.tr/tr/rss/default?cat=guncel', 'state_media', 'wire', true),
  ('TRT Haber', 'trt-haber', 'http://www.trthaber.com', 'http://www.trthaber.com/sondakika.rss', 'state_media', 'outlet', true),
  ('TRT World', 'trt-world', 'https://www.trtworld.com', 'https://www.trtworld.com/news/rss', 'state_media', 'outlet', true),
  ('A News', 'a-news', 'https://www.anews.com.tr', 'https://www.anews.com.tr/rss/news.xml', 'state_media', 'outlet', true),
  ('Daily Sabah', 'daily-sabah', 'https://www.dailysabah.com', 'https://www.dailysabah.com/rss/home-page', 'state_media', 'outlet', true),
  ('MFA Turkey', 'mfa-turkey', 'https://www.mfa.gov.tr', 'https://www.mfa.gov.tr/rss.en.mfa', 'state_media', 'niche', true),

  -- Center / Independent
  ('T24', 't24', 'https://t24.com.tr', 'https://t24.com.tr/rss', 'center', 'outlet', true),
  ('Diken', 'diken', 'https://www.diken.com.tr', 'https://www.diken.com.tr/feed/', 'center', 'outlet', true),
  ('Medyascope', 'medyascope', 'https://medyascope.tv', 'https://medyascope.tv/feed/', 'center', 'outlet', true),
  ('Journo', 'journo', 'https://journo.com.tr', 'https://journo.com.tr/feed', 'center', 'niche', true),
  ('Gazete Duvar', 'gazete-duvar', 'https://www.gazeteduvar.com.tr', 'https://www.gazeteduvar.com.tr/export/rss', 'center', 'outlet', true),
  ('Bianet', 'bianet', 'https://bianet.org', 'https://bianet.org/biamag.rss', 'center', 'outlet', true),
  ('Ekonomim', 'ekonomim', 'https://www.ekonomim.com', 'https://www.ekonomim.com/export/rss', 'center', 'niche', true),
  ('Dünya', 'dunya', 'https://www.dunya.com', 'https://www.dunya.com/rss?dunya', 'center', 'niche', true),
  ('Independent Türkçe', 'independent-turkce', 'https://www.indyturk.com', 'https://www.indyturk.com/rss.xml', 'center', 'outlet', true),
  ('Karar', 'karar', 'https://www.karar.com', 'https://www.karar.com/service/rss.php', 'center', 'outlet', true),
  ('Dokuz8 Haber', 'dokuz8-haber', 'https://www.dokuz8haber.net', 'https://www.dokuz8haber.net/rss', 'center', 'outlet', true),
  ('Fayn', 'fayn', 'https://www.fayn.press', 'https://www.fayn.press/rss/', 'center', 'outlet', true),
  ('Gazete Oksijen', 'gazete-oksijen', 'https://gazeteoksijen.com', 'https://gazeteoksijen.com/export/rss', 'center', 'outlet', true),
  ('Gazete Pencere', 'gazete-pencere', 'https://www.gazetepencere.com', 'https://www.gazetepencere.com/service/rss.php', 'center', 'outlet', true),
  ('Gerçek Gündem', 'gercek-gundem', 'https://www.gercekgundem.com', 'https://www.gercekgundem.com/rss', 'center', 'outlet', true),
  ('Onedio', 'onedio', 'https://onedio.com', 'https://onedio.com/Publisher/publisher-gundem.rss', 'center', 'aggregator', true),
  ('Habervakti', 'habervakti', 'https://www.habervakti.com', 'https://www.habervakti.com/rss', 'center', 'outlet', true),
  ('F5 Haber', 'f5-haber', 'https://www.f5haber.com', 'https://www.f5haber.com/export/rss', 'center', 'aggregator', true),
  ('Platform 24', 'platform-24', 'http://platform24.org', 'http://platform24.org/rss', 'center', 'niche', false),
  ('Açık Gazete', 'acik-gazete', 'https://www.acikgazete.com', 'https://www.acikgazete.com/feed/', 'center', 'outlet', true),
  ('Ajans Haber', 'ajans-haber', 'https://www.ajanshaber.com', 'https://www.ajanshaber.com/rss', 'center', 'aggregator', true),
  ('Haber3', 'haber3', 'https://www.haber3.com', 'https://www.haber3.com/rss', 'center', 'aggregator', true),
  ('Son Dakika', 'son-dakika', 'http://www.sondakika.com', 'http://rss.sondakika.com/rss_standart.asp', 'center', 'aggregator', false),
  ('Beyaz Gazete', 'beyaz-gazete', 'https://beyazgazete.com', 'https://beyazgazete.com/rss/guncel.xml', 'center', 'aggregator', true),
  ('Bloomberg HT', 'bloomberg-ht', 'http://www.bloomberght.com', 'http://www.bloomberght.com/rss', 'center', 'niche', true),
  ('Finansal Gündem', 'finansal-gundem', 'http://www.finansgundem.com', 'http://www.finansgundem.com/rss', 'center', 'niche', true),
  ('Investing.com TR', 'investing-com-tr', 'https://tr.investing.com', 'https://tr.investing.com/rss/news_288.rss', 'center', 'niche', true),
  ('Paraanaliz', 'paraanaliz', 'https://www.paraanaliz.com', 'https://www.paraanaliz.com/feed/', 'center', 'niche', false),
  ('AjansSpor', 'ajansspor', 'https://ajansspor.com', 'https://ajansspor.com/rss', 'center', 'niche', true),
  ('Fotospor', 'fotospor', 'https://www.fotospor.com', 'https://www.fotospor.com/feed/rss_sondakika.xml', 'center', 'niche', true),
  ('Kontraspor', 'kontraspor', 'https://kontraspor.com', 'https://kontraspor.com/rss', 'center', 'niche', true),
  ('TOBB', 'tobb', 'https://www.tobb.org.tr', 'https://www.tobb.org.tr/Sayfalar/RssFeeder.php?List=Haberler', 'center', 'niche', true),
  ('NewsLab Turkey', 'newslab-turkey', 'https://www.newslabturkey.org', 'https://www.newslabturkey.org/feed/', 'center', 'niche', true),
  ('İklim Haber', 'iklim-haber', 'https://www.iklimhaber.org', 'https://www.iklimhaber.org/feed/', 'center', 'niche', true),
  ('Hukuki Haber', 'hukuki-haber', 'https://www.hukukihaber.net', 'https://www.hukukihaber.net/rss', 'center', 'niche', true),
  ('Dijital Gaste', 'dijital-gaste', 'https://www.dijitalgaste.com', 'https://www.dijitalgaste.com/rss', 'center', 'outlet', true),
  ('dikGAZETE', 'dikgazete', 'https://www.dikgazete.com', 'https://www.dikgazete.com/xml/rss.xml', 'center', 'outlet', true),
  ('Gazete.net', 'gazete-net', 'https://gazete.net', 'https://gazete.net/rss', 'center', 'outlet', true),
  ('Haberport', 'haberport', 'https://www.haberport.com', 'https://www.haberport.com/rss/latest-posts', 'center', 'outlet', true),
  ('Bir Gazete', 'bir-gazete', 'https://www.birgazete.com', 'https://www.birgazete.com/feed', 'center', 'outlet', true),
  ('ABC Haber', 'abc-haber', 'https://abcgazetesi.com.tr', 'https://abcgazetesi.com.tr/rss', 'center', 'outlet', true),
  ('10Haber', '10haber', 'https://10haber.net', 'https://10haber.net/feed/', 'center', 'outlet', true),
  ('Aykırı', 'aykiri', 'https://www.aykiri.com.tr', 'https://www.aykiri.com.tr/rss.xml', 'center', 'outlet', true),
  ('Ayandon', 'ayandon', 'https://www.ayandon.com.tr', 'https://www.ayandon.com.tr/rss.xml', 'center', 'outlet', true),
  ('Haberet', 'haberet', 'https://www.haberet.com', 'https://www.haberet.com/export/rss', 'center', 'outlet', true),
  ('Haber.com', 'haber-com', 'https://www.haber.com', 'https://www.haber.com/rss', 'center', 'outlet', true),
  ('İşin Detayı', 'isin-detayi', 'https://www.isindetayi.com', 'https://www.isindetayi.com/rss/gundem', 'center', 'outlet', true),
  ('Kamudanhaber', 'kamudanhaber', 'https://www.kamudanhaber.net', 'https://www.kamudanhaber.net/rss', 'center', 'niche', true),
  ('Türkiye Haber Ajansı', 'turkiye-haber-ajansi', 'http://www.turkiyehaberajansi.com', 'http://www.turkiyehaberajansi.com/rss.xml', 'center', 'wire', true),
  ('Eko Seyir', 'eko-seyir', 'http://www.ekoseyir.com', 'http://www.ekoseyir.com/rss/piyasalar/248.xml', 'center', 'niche', false),
  ('Ay Gazete', 'ay-gazete', 'http://www.aygazete.com', 'http://www.aygazete.com/rss/gundem-haberleri', 'center', 'outlet', false),
  ('Haberiniz', 'haberiniz', 'https://haberiniz.com.tr', 'https://haberiniz.com.tr/feed/', 'center', 'outlet', true),

  -- Opposition-Leaning
  ('Sözcü', 'sozcu', 'https://www.sozcu.com.tr', 'https://www.sozcu.com.tr/feeds-rss-category-sozcu', 'opposition_leaning', 'outlet', true),
  ('Cumhuriyet', 'cumhuriyet', 'https://www.cumhuriyet.com.tr', 'https://www.cumhuriyet.com.tr/rss/son_dakika.xml', 'opposition_leaning', 'outlet', true),
  ('Halk TV', 'halk-tv', 'https://halktv.com.tr', 'https://halktv.com.tr/service/rss.php', 'opposition_leaning', 'outlet', true),
  ('Tele1', 'tele1', 'https://www.tele1.com.tr', 'https://www.tele1.com.tr/rss', 'opposition_leaning', 'outlet', true),
  ('Korkusuz', 'korkusuz', 'https://www.korkusuz.com.tr', 'https://www.korkusuz.com.tr/feeds/rss', 'opposition_leaning', 'outlet', true),
  ('Artı Gerçek', 'arti-gercek', 'https://artigercek.com', 'https://artigercek.com/service/rss.php', 'opposition_leaning', 'outlet', true),
  ('Kısa Dalga', 'kisa-dalga', 'https://kisadalga.net', 'https://kisadalga.net/service/rss.php', 'opposition_leaning', 'outlet', true),
  ('Demokrat Haber', 'demokrat-haber', 'https://www.demokrathaber.org', 'https://www.demokrathaber.org/rss', 'opposition_leaning', 'outlet', true),
  ('OdaTV', 'odatv', 'https://www.odatv.com', 'https://www.odatv.com/rss.xml', 'opposition_leaning', 'outlet', true),
  ('KRT TV', 'krt-tv', 'https://www.krttv.com.tr', 'https://www.krttv.com.tr/rss', 'opposition_leaning', 'outlet', true),
  ('Artı Bir TV', 'arti-bir-tv', 'http://www.haberartibir.com.tr', 'http://www.haberartibir.com.tr/rss.php', 'opposition_leaning', 'outlet', false),
  ('İleri Haber', 'ileri-haber', 'http://ilerihaber.org', 'http://ilerihaber.org/rss.xml', 'opposition_leaning', 'outlet', false),
  ('En Politik', 'en-politik', 'https://www.enpolitik.com', 'https://www.enpolitik.com/rss.xml', 'opposition_leaning', 'outlet', true),
  ('Medya Gazete', 'medya-gazete', 'https://www.medyagazete.com', 'https://www.medyagazete.com/rss/genel-0', 'opposition_leaning', 'outlet', true),
  ('Muhalif', 'muhalif', 'https://www.muhalif.com.tr', 'https://www.muhalif.com.tr/rss/genel-0', 'opposition_leaning', 'outlet', true),
  ('Elips Haber', 'elips-haber', 'https://www.elipshaber.com', 'https://www.elipshaber.com/rss', 'opposition_leaning', 'outlet', true),

  -- Opposition
  ('BirGün', 'birgun', 'https://www.birgun.net', 'https://www.birgun.net/rss/home', 'opposition', 'outlet', true),
  ('Evrensel', 'evrensel', 'https://www.evrensel.net', 'https://www.evrensel.net/rss/haber.xml', 'opposition', 'outlet', true),
  ('Serbestiyet', 'serbestiyet', 'https://serbestiyet.com', 'https://serbestiyet.com/feed/', 'opposition', 'outlet', true),
  ('Agos', 'agos', 'https://www.agos.com.tr', 'https://www.agos.com.tr/rss', 'opposition', 'outlet', true),
  ('Sol Haber', 'sol-haber', 'http://haber.sol.org.tr', 'http://haber.sol.org.tr/rss.xml', 'opposition', 'outlet', false),
  ('Sendika.Org', 'sendika-org', 'https://sendika.org', 'http://haberss.org/dosya/rss/sendika.org', 'opposition', 'outlet', false),
  ('Ekol TV', 'ekol-tv', 'https://www.ekoltv.com.tr', 'https://www.ekoltv.com.tr/service/rss.php', 'opposition', 'outlet', true),
  ('İşçi Haber', 'isci-haber', 'https://www.iscihaber.net', 'https://www.iscihaber.net/rss/news', 'opposition', 'niche', true),

  -- Nationalist
  ('Yeniçağ', 'yenicag', 'http://www.yenicaggazetesi.com.tr', 'http://www.yenicaggazetesi.com.tr/rss', 'nationalist', 'outlet', true),
  ('Aydınlık', 'aydinlik', 'https://www.aydinlik.com.tr', 'https://www.aydinlik.com.tr/feed', 'nationalist', 'outlet', true),
  ('Ortadoğu', 'ortadogu', 'https://www.ortadogugazetesi.com', 'https://www.ortadogugazetesi.com/rss', 'nationalist', 'outlet', false),
  ('Ulusal Kanal', 'ulusal-kanal', 'http://www.ulusalkanal.com.tr', 'http://www.ulusalkanal.com.tr/rss.php', 'nationalist', 'outlet', false),
  ('Bengütürk', 'benguturk', 'https://www.benguturk.com', 'https://www.benguturk.com/rss', 'nationalist', 'outlet', true),

  -- Islamist / Conservative
  ('Milli Gazete', 'milli-gazete', 'https://www.milligazete.com.tr', 'https://www.milligazete.com.tr/rss', 'islamist_conservative', 'outlet', true),
  ('Yeni Asya', 'yeni-asya', 'https://www.yeniasya.com.tr', 'https://www.yeniasya.com.tr/rss', 'islamist_conservative', 'outlet', false),
  ('Yeni Mesaj', 'yeni-mesaj', 'http://www.yenimesaj.com.tr', 'http://www.yenimesaj.com.tr/rss.php', 'islamist_conservative', 'outlet', true),
  ('Diyanet Haber', 'diyanet-haber', 'https://www.diyanethaber.com.tr', 'https://www.diyanethaber.com.tr/rss', 'islamist_conservative', 'niche', true),
  ('Doğru Haber', 'dogru-haber', 'https://dogruhaber.com.tr', 'https://dogruhaber.com.tr/rss', 'islamist_conservative', 'outlet', true),
  ('İlke TV', 'ilke-tv', 'https://ilketv.com.tr', 'https://ilketv.com.tr/feed/', 'islamist_conservative', 'outlet', true),

  -- Pro-Kurdish
  ('Mezopotamya Ajansı', 'mezopotamya-ajansi', 'https://mezopotamyaajansi43.com', 'https://mezopotamyaajansi43.com/feed/', 'pro_kurdish', 'wire', false),
  ('BHA', 'bha', 'https://bha.net.tr', 'https://bha.net.tr/rss', 'pro_kurdish', 'wire', true),
  ('Rûdaw Türkçe', 'rudaw-turkce', 'http://rudaw.net', 'http://rudaw.net/turkish/rss?type=top', 'pro_kurdish', 'outlet', true),

  -- International
  ('BBC Türkçe', 'bbc-turkce', 'https://www.bbc.com/turkce', 'https://feeds.bbci.co.uk/turkce/rss.xml', 'international', 'outlet', true),
  ('DW Türkçe', 'dw-turkce', 'https://www.dw.com/tr', 'https://rss.dw.com/rdf/rss-tur-all', 'international', 'outlet', true),
  ('Euronews Türkçe', 'euronews-turkce', 'https://tr.euronews.com', 'https://tr.euronews.com/rss', 'international', 'outlet', true),
  ('VOA Türkçe', 'voa-turkce', 'https://www.voaturkce.com', 'https://www.voaturkce.com/api/zr$ymetqvi', 'international', 'outlet', false),
  ('Sputnik Türkçe', 'sputnik-turkce', 'https://tr.sputniknews.com', 'https://tr.sputniknews.com/export/rss2/archive/index.xml', 'international', 'outlet', true),
  ('CGTN Türk', 'cgtn-turk', 'https://www.cgtnturk.com', 'https://www.cgtnturk.com/rss', 'international', 'outlet', true),
  ('Al Ain Türkçe', 'al-ain-turkce', 'https://tr.al-ain.com', 'https://tr.al-ain.com/feed', 'international', 'outlet', true),
  ('Al Jazeera Turk', 'al-jazeera-turk', 'http://aljazeera.com.tr', 'http://aljazeera.com.tr/rss.xml', 'international', 'outlet', false),
  ('Ahval News', 'ahval-news', 'https://ahvalnews.com', 'https://ahvalnews.com/rss.xml', 'international', 'outlet', false),
  ('Hürriyet Daily News', 'hurriyet-daily-news', 'https://www.hurriyetdailynews.com', 'https://www.hurriyetdailynews.com/rss', 'international', 'outlet', true),
  ('Türkiye Today', 'turkiye-today', 'https://www.turkiyetoday.com', 'https://www.turkiyetoday.com/feed/', 'international', 'outlet', false)
on conflict (slug) do update set
  name = excluded.name,
  url = excluded.url,
  rss_url = excluded.rss_url,
  bias = excluded.bias,
  kind = excluded.kind,
  active = excluded.active;
